phrase:
  project_id: 6480e2728c93142480a902a6d3d91d25
  push:
    sources:
    - file: "./locales/en.json"
      params:
        file_format: simple_json
        locale_id: 2af680c3fb559bb7edabd6105d2d7cfd
        autotranslate: true
        format_options:
          enable_pluralization: false
  pull:
    targets:
    - file: "./locales/cs.json"
      params:
        file_format: simple_json
        locale_id: 8d02b5d44a7ece6d315688046cc89954
        include_empty_translations: true
